# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        ##########################################

        migrations.CreateModel(
            name='AuditorBeforeTypingDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Before Typing Delay Auditors',
                'verbose_name': 'Before Typing Delay Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorClicksTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Clicks Total Auditors',
                'verbose_name': 'Clicks Total Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorClicksSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Clicks Specific Auditors',
                'verbose_name': 'Clicks Specific Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorFocusChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Focus Changes Auditors',
                'verbose_name': 'Focus Changes Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorKeypressesTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Keypresses Total Auditors',
                'verbose_name': 'Keypresses Total Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorKeypressesSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Keypresses Specific Auditors',
                'verbose_name': 'Keypresses Specific Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorMouseMovementTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Mouse Movement Total Auditors',
                'verbose_name': 'Mouse Movement Total Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorMouseMovementSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Mouse Movement Specific Auditors',
                'verbose_name': 'Mouse Movement Specific Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorTotalTaskTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Total Task Time Auditors',
                'verbose_name': 'Total Task Time Auditor',
                'ordering': ['task', '-updated', '-created'],
                'abstract': False,
            },
        ),

        ##########################################

        migrations.CreateModel(
            name='AuditorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='StepData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='StepMultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('step_num', models.IntegerField(help_text='Controls the order that steps linked to a task are to be taken in by the user', verbose_name='Step Number')),
                ('title', models.CharField(help_text='Title for multiple choice prompt. Choose carefully. This and associated responses are not allowed to change after the first user has responded to this multiple choice step. Then, you must create a new Multiple Choice Step', max_length=144, verbose_name='Title')),
                ('text', models.TextField(help_text='The text to go along with your multiple choice prompt. Choose carefully. This and associated responses are not allowed to change after the first user has responded to this multiple choice step. Then, you must create a new Multiple Choice Step', verbose_name='Multiple Choice Text')),
                ('randomize_order', models.BooleanField(default=False, help_text='Randomizes the order in which responses are presented to the user under a Multiple Choice Step if selected', verbose_name='Randomize Response Order')),
            ],
            options={
                'verbose_name_plural': 'Steps',
                'verbose_name': 'Multiple Choice Step',
                'ordering': ['task', 'step_num', '-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepMultipleChoiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('text', models.TextField(help_text='Text for one of the responses to a Multiple Choice Step', verbose_name='Multiple Choice Response Text')),
                ('order', models.IntegerField(blank=True, help_text='Controls the order that responses linked to a Multiple Choice Step are to be rendered. The field can be left blank but this only really makes sense if you randomize order of responses in the Multiple Choice Step', null=True, verbose_name='Response Number')),
                ('multiple_choice_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.StepMultipleChoice', verbose_name='Associated Multiple Choice Step for Response')),
            ],
            options={
                'verbose_name_plural': 'Steps',
                'verbose_name': 'Multiple Choice Step Response',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('number_simultaneous_users', models.IntegerField(help_text='Number of users who need to be in the lobby and ready to begin before they may start the task', validators=[survey.models.not_less_than_one], verbose_name='Number of simultaneous users')),
                ('survey_name', models.CharField(help_text="This is exposed to the user: Name of the survey they're taking", max_length=144, verbose_name='Survey Name')),
                ('owners', models.ManyToManyField(help_text='Users with permission to view and modify', to=settings.AUTH_USER_MODEL, verbose_name='Owners')),
                ('task_dependencies', models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this task by a given user', to='survey.Task', verbose_name='Task Dependencies')),
            ],
            options={
                'verbose_name': 'Interactive Task',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='TaskInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task', models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task')),
            ],
            options={
                'verbose_name': 'Task Interaction',
            },
        ),

        ##########################################

        migrations.CreateModel(
            name='AuditorBeforeTypingDelayData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('milliseconds', models.IntegerField(help_text='total time in milliseconds that the user took before typing', null=True, blank=True, verbose_name='total task time')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorClicksTotalData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('count', models.IntegerField(help_text='total number of times a user clicked', verbose_name='clicks total')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorClicksSpecificData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('type_', models.TextField(help_text='DOM type of element that was clicked', null=True, blank=True, verbose_name='clicks specific type')),
                ('id_', models.TextField(help_text='DOM ID of element that was clicked', null=True, blank=True, verbose_name='clicks specific id')),
                ('class_', models.TextField(help_text='DOM class of element that was clicked', null=True, blank=True, verbose_name='clicks specific class')),
                ('name_', models.TextField(help_text='DOM name of element that was clicked', null=True, blank=True, verbose_name='clicks specific name')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorFocusChangesData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('time', models.IntegerField(help_text='timestamps of whenever the user switches out of focus', verbose_name='focus changes times')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorKeypressesTotalData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('count', models.IntegerField(help_text='total number of times a user pressed a key', verbose_name='keypresses total')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorKeypressesSpecificData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('key', models.TextField(help_text='specific keys pressed by the user', verbose_name='keypresses specific')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorMouseMovementTotalData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('amount', models.IntegerField(help_text='total number of pixels traversed by the cursor due to user moving mouse', verbose_name='mouse movement total')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorMouseMovementSpecificData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('x', models.IntegerField(help_text='ending x coordinate of mouse whenever user moves mouse', verbose_name='mouse movement x coordinate')),
                ('y', models.IntegerField(help_text='ending y coordinate of mouse whenever user moves mouse', verbose_name='mouse movement y coordinate')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),
        migrations.CreateModel(
            name='AuditorTotalTaskTimeData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('milliseconds', models.IntegerField(help_text='total time in milliseconds that the user spent on the task page', verbose_name='total task time')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.auditordata',),
        ),

        ##########################################

        migrations.CreateModel(
            name='StepMultipleChoiceData',
            fields=[
                ('stepdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.StepData')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated', '-created'],
            },
            bases=('survey.stepdata',),
        ),
        migrations.AddField(
            model_name='stepmultiplechoice',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='task_interaction_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.TaskInteraction'),
        ),

        ##########################################

        migrations.AddField(
            model_name='auditorbeforetypingdelay',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditorclickstotal',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditorclicksspecific',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditorfocuschanges',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditorkeypressestotal',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditorkeypressesspecific',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditormousemovementtotal',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditormousemovementspecific',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),
        migrations.AddField(
            model_name='auditortotaltasktime',
            name='task',
            field=models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task'),
        ),

        ##########################################

        migrations.AddField(
            model_name='auditordata',
            name='task_interaction_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.TaskInteraction'),
        ),
        migrations.AddField(
            model_name='stepmultiplechoicedata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.StepMultipleChoice'),
        ),
        migrations.AddField(
            model_name='stepmultiplechoicedata',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.StepMultipleChoiceResponse'),
        ),

        #########################################

        migrations.AddField(
            model_name='auditorbeforetypingdelaydata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorBeforeTypingDelay'),
        ),
        migrations.AddField(
            model_name='auditorclickstotaldata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorClicksTotal'),
        ),
        migrations.AddField(
            model_name='auditorclicksspecificdata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorClicksTotal'),
        ),
        migrations.AddField(
            model_name='auditorfocuschangesdata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorClicksTotal'),
        ),
        migrations.AddField(
            model_name='auditorkeypressestotaldata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorClicksTotal'),
        ),
        migrations.AddField(
            model_name='auditorkeypressesspecificdata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorClicksTotal'),
        ),
        migrations.AddField(
            model_name='auditormousemovementtotaldata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorClicksTotal'),
        ),
        migrations.AddField(
            model_name='auditormousemovementspecificdata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorClicksTotal'),
        ),
        migrations.AddField(
            model_name='auditortotaltasktimedata',
            name='general_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorTotalTaskTime'),
        ),

        ##########################################
    ]
