# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task', models.ForeignKey(help_text='Task that this is linked to', on_delete=django.db.models.deletion.CASCADE, to='survey.Task', verbose_name='Associated Task')),
            ],
            options={
                'verbose_name': 'URL Auditor',
                'ordering': ['task', '-updated', '-created'],
                'verbose_name_plural': 'URL Auditors',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditorURLData',
            fields=[
                ('auditordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AuditorData')),
                ('url', models.TextField(help_text='URL of the current task', verbose_name='URL')),
                ('general_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AuditorURL')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
            bases=('survey.auditordata',),
        ),
    ]
