version: "2"
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
      - "8082"
      - "8083"
      - "8084"
      - "8085"
      - "8086"
      - "8087"
      - "8088"
      - "8089"
      - "8090"
    env_file: .test-env
    depends_on:
      - "postgres"
      - "selenium"

  postgres:
    restart: always
    build: ./postgres/
    volumes_from:
      - data
    expose:
      - "5432"

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  selenium:
    image: selenium/standalone-chrome
