version: "2"
services:
  web:
    build: ./web
    expose:
      - "8000"
      - "8082"
      - "8083"
      - "8084"
      - "8085"
      - "8086"
      - "8087"
      - "8088"
      - "8089"
      - "8090"
      - "8091"
      - "8092"
      - "8093"
      - "8094"
      - "8095"
      - "8096"
      - "8097"
    env_file: .test-env
    depends_on:
      - "postgres"
      - "selenium-chrome"
    command: ./test.sh

  postgres:
    build: ./postgres/
    volumes_from:
      - data
    expose:
      - "5432"

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  selenium-chrome:
    image: selenium/standalone-chrome
