version: "2"
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    ports:
      - "8888:8888"
    env_file: .env
    environment:
      - DEBUG
      - SECRET_KEY
      - DOMAIN
      - NOTEBOOK_PASS_HASH
    depends_on:
      - "postgres"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - static_data
    depends_on:
      - "web"
      - "static_data"

  postgres:
    restart: always
    build: ./postgres/
    volumes_from:
      - data
    expose:
      - "5432"

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  static_data:
    build: ./web
    env_file: .env
    volumes:
      - /usr/build/app/static
    environment:
      - DEBUG
      - SECRET_KEY
      - DOMAIN
    command: "/bin/sh collect-static.sh"

