version: "2"
services:
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile-Science
    ports:
      - "8888:8888"
    env_file: .env
    environment:
      - NOTEBOOK_PASS_HASH
    depends_on:
      - "postgres"

  postgres:
    restart: always
    build: ./postgres/
    volumes_from:
      - data
    expose:
      - "5432"

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"
